//! Build script: embed the executable icon into the Windows resource table.
//!
//! `runic.rc` references `assets/runic.ico` (the Raidho rune, generated by
//! `assets/gen_icon.py` from the same stroke geometry the tray paints at
//! runtime), which becomes the app icon shown by Explorer, alt-tab and the
//! installer. Gated on the *target* OS so a cross-build from Linux
//! (`cargo xwin`) still embeds it; a no-op for any non-Windows target.

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    println!("cargo:rerun-if-changed=runic.rc");
    println!("cargo:rerun-if-changed=assets/runic.ico");
    embed_resource::compile("runic.rc", embed_resource::NONE);
}
